### ISSUE TITLE
Unable to import cypress-autostub

### ISSUE THREAD

**Issue by manipise** [dan-cooke/cypress-autostub#8]
Hi team 
trying to use the plug for auto mocking but at very first its failing as not mentioned in task 
but as per the document there is not such option to mention in task 
```
 CypressError: `cy.task('getGlobalConfig')` failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

Fix this in your plugins file here:
```

**Comment by dan-cooke** [comment]
@manipise what version of cypress are you using?

**Comment by dan-cooke** [comment]
Closing this.
